import assert from "node:assert/strict";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { request as httpRequest } from "node:http";
import { join, resolve } from "node:path";
import { AddressInfo } from "node:net";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { startWebServer } from "../src/index.js";

async function withServer(run: (baseUrl: string) => Promise<void>): Promise<void> {
  const server = startWebServer(0);
  await new Promise<void>((resolveReady) => server.once("listening", () => resolveReady()));
  const address = server.address() as AddressInfo;
  const baseUrl = `http://127.0.0.1:${address.port}`;
  try {
    await run(baseUrl);
  } finally {
    await new Promise<void>((resolveClose, rejectClose) => {
      server.close((err) => {
        if (err) rejectClose(err);
        else resolveClose();
      });
    });
  }
}

test("web root serves inbox html shell", async () => {
  await withServer(async (baseUrl) => {
    const res = await fetch(baseUrl + "/");
    assert.equal(res.status, 200);
    const text = await res.text();
    const inlineScriptMatch = text.match(/<script>([\s\S]*?)<\/script>/u);
    assert.ok(inlineScriptMatch?.[1], "expected inline script in inbox shell");
    assert.doesNotThrow(() => {
      // 编译检查：防止重复 const/语法错误被静态文本断言漏掉
      new Function(inlineScriptMatch[1]);
    });
    assert.match(text, /Read→Do Inbox/u);
    assert.match(text, /从信息堆积到可执行决策/u);
    assert.match(text, /Clear Filters/u);
    assert.match(text, /Preview Retry/u);
    assert.match(text, /Retry Failed/u);
    assert.match(text, /id="selectionHint"/u);
    assert.match(text, /Selected: none/u);
    assert.match(text, /id="ahaPulseBtn"/u);
    assert.match(text, /Aha Pulse: —/u);
    assert.match(text, /Aha Pulse: waiting for items\./u);
    assert.match(text, /Shift\+Click run lead action/u);
    assert.match(text, /Alt\+Click focus #2/u);
    assert.match(text, /Preview Archive/u);
    assert.match(text, /Preview Unarchive/u);
    assert.match(text, /Preview Offset/u);
    assert.match(text, /press \//u);
    assert.match(text, /Press \? for shortcuts/u);
    assert.match(text, /Shortcuts \(\?\)/u);
    assert.match(text, /id="shortcutHintBtn"/u);
    assert.match(text, /aria-expanded="false"/u);
    assert.match(text, /title="Shortcuts: \/ Search · H Toggle Shortcut Guide · J Select next item · K Select previous item · F Focus Mode · A Advanced Panels · V Toggle Detail Mode · P Focus Priority · Shift\+P Focus Priority \(reverse\) · G Edit Context Filters · N Focus Recommended Item · Z Focus Top Aha Item · Shift\+N Focus Next Aha Candidate · Alt\+N Focus Previous Aha Candidate · Shift\+Z Focus 2nd Aha Candidate · Alt\+Z Toggle Duel Pair · Q Run Top Aha Action · Alt\+Q Run Duel Pair Actions · Shift\+Q Copy Duel Action Plan · Shift\+S Copy Duel Snapshot · Alt\+C Copy Duel Call · Alt\+S Copy Duel Signals · Alt\+M Run Duel Call · Alt\+P Run Signal Protocol · Alt\+L Run Signal Command · Alt\+Shift\+L Copy Signal Command · Alt\+Shift\+P Copy Signal Protocol · E Open Aha Rival · Shift\+E Copy Aha Duel · Alt\+E Run Rival Action · Shift\+D Copy Decision Brief · Alt\+D Download Decision Brief · M Run Primary Item Action · O Open Selected Source · Y Copy Selected Source · I Copy Selected Context · U Copy Aha Snapshot · Shift\+U Download Aha Snapshot · B Open First Blocked · X Rescue Last Retry · Shift\+G Clear Step Focus · Esc Clear Step Focus · 1 Focus extract step · 2 Focus pipeline step · 3 Focus export step · 0 Focus unknown step · Alt\+1 Focus Priority Smart · Alt\+2 Focus Priority Query First · Alt\+3 Focus Priority Step First · \[ Previous Recovery Run · \] Next Recovery Run · L Latest Recovery Run · C Clear Filters · Shift\+C Reset Controls · T Toggle Auto Refresh · W Run Worker Once · R Refresh · Shift\+R Reset Aha Cycle · \? Show shortcuts"/u);
    assert.match(text, /aria-label="Shortcuts: \/ Search · H Toggle Shortcut Guide · J Select next item · K Select previous item · F Focus Mode · A Advanced Panels · V Toggle Detail Mode · P Focus Priority · Shift\+P Focus Priority \(reverse\) · G Edit Context Filters · N Focus Recommended Item · Z Focus Top Aha Item · Shift\+N Focus Next Aha Candidate · Alt\+N Focus Previous Aha Candidate · Shift\+Z Focus 2nd Aha Candidate · Alt\+Z Toggle Duel Pair · Q Run Top Aha Action · Alt\+Q Run Duel Pair Actions · Shift\+Q Copy Duel Action Plan · Shift\+S Copy Duel Snapshot · Alt\+C Copy Duel Call · Alt\+S Copy Duel Signals · Alt\+M Run Duel Call · Alt\+P Run Signal Protocol · Alt\+L Run Signal Command · Alt\+Shift\+L Copy Signal Command · Alt\+Shift\+P Copy Signal Protocol · E Open Aha Rival · Shift\+E Copy Aha Duel · Alt\+E Run Rival Action · Shift\+D Copy Decision Brief · Alt\+D Download Decision Brief · M Run Primary Item Action · O Open Selected Source · Y Copy Selected Source · I Copy Selected Context · U Copy Aha Snapshot · Shift\+U Download Aha Snapshot · B Open First Blocked · X Rescue Last Retry · Shift\+G Clear Step Focus · Esc Clear Step Focus · 1 Focus extract step · 2 Focus pipeline step · 3 Focus export step · 0 Focus unknown step · Alt\+1 Focus Priority Smart · Alt\+2 Focus Priority Query First · Alt\+3 Focus Priority Step First · \[ Previous Recovery Run · \] Next Recovery Run · L Latest Recovery Run · C Clear Filters · Shift\+C Reset Controls · T Toggle Auto Refresh · W Run Worker Once · R Refresh · Shift\+R Reset Aha Cycle · \? Show shortcuts"/u);
    assert.match(text, /Shortcuts: \/ Search · H Toggle Shortcut Guide · J Select next item · K Select previous item · F Focus Mode · A Advanced Panels · V Toggle Detail Mode · P Focus Priority · Shift\+P Focus Priority \(reverse\) · G Edit Context Filters · N Focus Recommended Item · Z Focus Top Aha Item · Shift\+N Focus Next Aha Candidate · Alt\+N Focus Previous Aha Candidate · Shift\+Z Focus 2nd Aha Candidate · Alt\+Z Toggle Duel Pair · Q Run Top Aha Action · Alt\+Q Run Duel Pair Actions · Shift\+Q Copy Duel Action Plan · Shift\+S Copy Duel Snapshot · Alt\+C Copy Duel Call · Alt\+S Copy Duel Signals · Alt\+M Run Duel Call · Alt\+P Run Signal Protocol · Alt\+L Run Signal Command · Alt\+Shift\+L Copy Signal Command · Alt\+Shift\+P Copy Signal Protocol · E Open Aha Rival · Shift\+E Copy Aha Duel · Alt\+E Run Rival Action · Shift\+D Copy Decision Brief · Alt\+D Download Decision Brief · M Run Primary Item Action · O Open Selected Source · Y Copy Selected Source · I Copy Selected Context · U Copy Aha Snapshot · Shift\+U Download Aha Snapshot · B Open First Blocked · X Rescue Last Retry · Shift\+G Clear Step Focus · Esc Clear Step Focus · 1 Focus extract step · 2 Focus pipeline step · 3 Focus export step · 0 Focus unknown step · Alt\+1 Focus Priority Smart · Alt\+2 Focus Priority Query First · Alt\+3 Focus Priority Step First · \[ Previous Recovery Run · \] Next Recovery Run · L Latest Recovery Run · C Clear Filters · Shift\+C Reset Controls · T Toggle Auto Refresh · W Run Worker Once · R Refresh · Shift\+R Reset Aha Cycle · \? Show shortcuts/u);
    assert.match(text, /id="shortcutPanelBackdrop"/u);
    assert.match(text, /id="shortcutPanelCloseBtn"/u);
    assert.match(text, /Shortcut Guide/u);
    assert.match(text, /Use these keys to move from reading to doing faster/u);
    assert.match(text, /id="shortcutPanelList"/u);
    assert.match(text, /<kbd>\/<\/kbd><span>Search<\/span>/u);
    assert.match(text, /<kbd>H<\/kbd><span>Toggle Shortcut Guide<\/span>/u);
    assert.match(text, /<kbd>J<\/kbd><span>Select next item<\/span>/u);
    assert.match(text, /<kbd>K<\/kbd><span>Select previous item<\/span>/u);
    assert.match(text, /<kbd>V<\/kbd><span>Toggle Detail Mode<\/span>/u);
    assert.match(text, /<kbd>P<\/kbd><span>Focus Priority<\/span>/u);
    assert.match(text, /<kbd>Shift\+P<\/kbd><span>Focus Priority \(reverse\)<\/span>/u);
    assert.match(text, /<kbd>G<\/kbd><span>Edit Context Filters<\/span>/u);
    assert.match(text, /<kbd>N<\/kbd><span>Focus Recommended Item<\/span>/u);
    assert.match(text, /<kbd>Z<\/kbd><span>Focus Top Aha Item<\/span>/u);
    assert.match(text, /<kbd>Shift\+N<\/kbd><span>Focus Next Aha Candidate<\/span>/u);
    assert.match(text, /<kbd>Alt\+N<\/kbd><span>Focus Previous Aha Candidate<\/span>/u);
    assert.match(text, /<kbd>Shift\+Z<\/kbd><span>Focus 2nd Aha Candidate<\/span>/u);
    assert.match(text, /<kbd>Alt\+Z<\/kbd><span>Toggle Duel Pair<\/span>/u);
    assert.match(text, /<kbd>Q<\/kbd><span>Run Top Aha Action<\/span>/u);
    assert.match(text, /<kbd>Alt\+Q<\/kbd><span>Run Duel Pair Actions<\/span>/u);
    assert.match(text, /<kbd>Shift\+Q<\/kbd><span>Copy Duel Action Plan<\/span>/u);
    assert.match(text, /<kbd>Shift\+S<\/kbd><span>Copy Duel Snapshot<\/span>/u);
    assert.match(text, /<kbd>Alt\+C<\/kbd><span>Copy Duel Call<\/span>/u);
    assert.match(text, /<kbd>Alt\+S<\/kbd><span>Copy Duel Signals<\/span>/u);
    assert.match(text, /<kbd>Alt\+M<\/kbd><span>Run Duel Call<\/span>/u);
    assert.match(text, /<kbd>Alt\+P<\/kbd><span>Run Signal Protocol<\/span>/u);
    assert.match(text, /<kbd>Alt\+L<\/kbd><span>Run Signal Command<\/span>/u);
    assert.match(text, /<kbd>Alt\+Shift\+L<\/kbd><span>Copy Signal Command<\/span>/u);
    assert.match(text, /<kbd>Alt\+Shift\+P<\/kbd><span>Copy Signal Protocol<\/span>/u);
    assert.match(text, /<kbd>E<\/kbd><span>Open Aha Rival<\/span>/u);
    assert.match(text, /<kbd>Shift\+E<\/kbd><span>Copy Aha Duel<\/span>/u);
    assert.match(text, /<kbd>Alt\+E<\/kbd><span>Run Rival Action<\/span>/u);
    assert.match(text, /<kbd>Shift\+D<\/kbd><span>Copy Decision Brief<\/span>/u);
    assert.match(text, /<kbd>Alt\+D<\/kbd><span>Download Decision Brief<\/span>/u);
    assert.match(text, /<kbd>M<\/kbd><span>Run Primary Item Action<\/span>/u);
    assert.match(text, /<kbd>O<\/kbd><span>Open Selected Source<\/span>/u);
    assert.match(text, /<kbd>Y<\/kbd><span>Copy Selected Source<\/span>/u);
    assert.match(text, /<kbd>I<\/kbd><span>Copy Selected Context<\/span>/u);
    assert.match(text, /<kbd>U<\/kbd><span>Copy Aha Snapshot<\/span>/u);
    assert.match(text, /<kbd>Shift\+U<\/kbd><span>Download Aha Snapshot<\/span>/u);
    assert.match(text, /<kbd>B<\/kbd><span>Open First Blocked<\/span>/u);
    assert.match(text, /<kbd>X<\/kbd><span>Rescue Last Retry<\/span>/u);
    assert.match(text, /<kbd>Shift\+G<\/kbd><span>Clear Step Focus<\/span>/u);
    assert.match(text, /<kbd>Esc<\/kbd><span>Clear Step Focus<\/span>/u);
    assert.match(text, /<kbd>1<\/kbd><span>Focus extract step<\/span>/u);
    assert.match(text, /<kbd>2<\/kbd><span>Focus pipeline step<\/span>/u);
    assert.match(text, /<kbd>3<\/kbd><span>Focus export step<\/span>/u);
    assert.match(text, /<kbd>0<\/kbd><span>Focus unknown step<\/span>/u);
    assert.match(text, /<kbd>Alt\+1<\/kbd><span>Focus Priority Smart<\/span>/u);
    assert.match(text, /<kbd>Alt\+2<\/kbd><span>Focus Priority Query First<\/span>/u);
    assert.match(text, /<kbd>Alt\+3<\/kbd><span>Focus Priority Step First<\/span>/u);
    assert.match(text, /<kbd>\[<\/kbd><span>Previous Recovery Run<\/span>/u);
    assert.match(text, /<kbd>\]<\/kbd><span>Next Recovery Run<\/span>/u);
    assert.match(text, /<kbd>L<\/kbd><span>Latest Recovery Run<\/span>/u);
    assert.match(text, /<kbd>C<\/kbd><span>Clear Filters<\/span>/u);
    assert.match(text, /<kbd>Shift\+C<\/kbd><span>Reset Controls<\/span>/u);
    assert.match(text, /<kbd>T<\/kbd><span>Toggle Auto Refresh<\/span>/u);
    assert.match(text, /<kbd>W<\/kbd><span>Run Worker Once<\/span>/u);
    assert.match(text, /<kbd>Shift\+R<\/kbd><span>Reset Aha Cycle<\/span>/u);
    assert.match(text, /id="queueHighlights"/u);
    assert.match(text, /id="queueFlowPulse"/u);
    assert.match(text, /Pipeline Pulse/u);
    assert.match(text, /Track capture → ship momentum/u);
    assert.match(text, /Flow health:/u);
    assert.match(text, /View Blocked/u);
    assert.match(text, /Open First Blocked/u);
    assert.match(text, /Rescue Last Retry/u);
    assert.match(text, /id="ahaNudge"/u);
    assert.match(text, /Aha Now/u);
    assert.match(text, /spotlight-note/u);
    assert.match(text, /Focus Recommended Item/u);
    assert.match(text, /Focus Top Aha \(Z\)/u);
    assert.match(text, /Focus Next Aha \(Shift\+N\)/u);
    assert.match(text, /Focus Previous Aha \(Alt\+N\)/u);
    assert.match(text, /Focus 2nd Aha \(Shift\+Z\)/u);
    assert.match(text, /Run Top Aha Action \(Q\)/u);
    assert.match(text, /Copy Aha Snapshot \(U\)/u);
    assert.match(text, /Copy Aha Story/u);
    assert.match(text, /Download Aha Snapshot \(Shift\+U\)/u);
    assert.match(text, /Reset Aha Cycle \(Shift\+R\)/u);
    assert.match(text, /Top Aha Candidates/u);
    assert.match(text, /Open Candidate/u);
    assert.match(text, /nudge-candidate-chip/u);
    assert.match(text, /nudge-candidate-chip\.is-top/u);
    assert.match(text, /nudge-heatmap/u);
    assert.match(text, /Aha Heatmap/u);
    assert.match(text, /nudge-heat-chip/u);
    assert.match(text, /nudge-heat-delta/u);
    assert.match(text, /nudge-heat-momentum/u);
    assert.match(text, /nudge-heat-trend/u);
    assert.match(text, /trend-bars/u);
    assert.match(text, /trend-bar/u);
    assert.match(text, /Momentum Trend/u);
    assert.match(text, /Hot\+Strong/u);
    assert.match(text, /nudge-story/u);
    assert.match(text, /nudge-brief/u);
    assert.match(text, /Decision Brief Preview/u);
    assert.match(text, /Brief Context/u);
    assert.match(text, /Aha Decision Brief/u);
    assert.match(text, /Aha Storyline/u);
    assert.match(text, /Storyline:/u);
    assert.match(text, /Lead #/u);
    assert.match(text, /nudge-duel/u);
    assert.match(text, /Aha Duel/u);
    assert.match(text, /Duel:/u);
    assert.match(text, /nudge-duel-gap/u);
    assert.match(text, /nudge-duel-edge/u);
    assert.match(text, /nudge-duel-call/u);
    assert.match(text, /nudge-duel-call-trend/u);
    assert.match(text, /nudge-duel-call-confidence/u);
    assert.match(text, /nudge-duel-call-stability/u);
    assert.match(text, /nudge-duel-call-risk/u);
    assert.match(text, /nudge-duel-call-sequence/u);
    assert.match(text, /nudge-duel-signal/u);
    assert.match(text, /nudge-duel-signal-pulse/u);
    assert.match(text, /nudge-duel-signal-volatility/u);
    assert.match(text, /nudge-duel-signal-outlook/u);
    assert.match(text, /nudge-duel-signal-regime/u);
    assert.match(text, /nudge-duel-signal-conviction/u);
    assert.match(text, /nudge-duel-signal-handoff/u);
    assert.match(text, /nudge-duel-signal-handoff-trend/u);
    assert.match(text, /nudge-duel-signal-handoff-chart/u);
    assert.match(text, /nudge-duel-signal-handoff-momentum/u);
    assert.match(text, /nudge-duel-signal-consensus/u);
    assert.match(text, /nudge-duel-signal-consensus-trend/u);
    assert.match(text, /nudge-duel-signal-consensus-chart/u);
    assert.match(text, /nudge-duel-signal-consensus-momentum/u);
    assert.match(text, /nudge-duel-signal-consensus-risk/u);
    assert.match(text, /nudge-duel-signal-consensus-stability/u);
    assert.match(text, /nudge-duel-signal-consensus-readiness/u);
    assert.match(text, /nudge-duel-signal-consensus-window/u);
    assert.match(text, /nudge-duel-signal-consensus-guardrail/u);
    assert.match(text, /nudge-duel-signal-consensus-trigger/u);
    assert.match(text, /nudge-duel-signal-consensus-protocol/u);
    assert.match(text, /nudge-duel-signal-consensus-protocol-confidence/u);
    assert.match(text, /nudge-duel-signal-consensus-protocol-trend/u);
    assert.match(text, /nudge-duel-signal-consensus-protocol-risk/u);
    assert.match(text, /nudge-duel-signal-consensus-protocol-regime/u);
    assert.match(text, /nudge-duel-signal-consensus-protocol-cadence/u);
    assert.match(text, /nudge-duel-signal-consensus-protocol-pressure/u);
    assert.match(text, /nudge-duel-signal-consensus-protocol-command/u);
    assert.match(text, /nudge-duel-signal-consensus-protocol-script/u);
    assert.match(text, /nudge-duel-signal-consensus-protocol-chart/u);
    assert.match(text, /nudge-duel-signal-chart/u);
    assert.match(text, /nudge-duel-snapshot/u);
    assert.match(text, /nudge-duel-plan/u);
    assert.match(text, /nudge-duel-trend/u);
    assert.match(text, /Duel Gap/u);
    assert.match(text, /Duel Edge/u);
    assert.match(text, /Duel Call/u);
    assert.match(text, /Duel Call Trend/u);
    assert.match(text, /Duel Call Confidence/u);
    assert.match(text, /Duel Call Stability/u);
    assert.match(text, /Duel Call Shift Risk/u);
    assert.match(text, /Duel Call Sequence/u);
    assert.match(text, /Duel Signal Index/u);
    assert.match(text, /Duel Signal Pulse/u);
    assert.match(text, /Duel Signal Volatility/u);
    assert.match(text, /Duel Signal Outlook/u);
    assert.match(text, /Duel Signal Regime/u);
    assert.match(text, /Duel Signal Conviction/u);
    assert.match(text, /Duel Signal Handoff/u);
    assert.match(text, /Duel Signal Handoff Trend/u);
    assert.match(text, /Duel Signal Handoff Momentum/u);
    assert.match(text, /Duel Signal Consensus/u);
    assert.match(text, /Duel Signal Consensus Trend/u);
    assert.match(text, /Duel Signal Consensus Momentum/u);
    assert.match(text, /Duel Signal Consensus Risk/u);
    assert.match(text, /Duel Signal Consensus Stability/u);
    assert.match(text, /Duel Signal Consensus Readiness/u);
    assert.match(text, /Duel Signal Consensus Window/u);
    assert.match(text, /Duel Signal Consensus Guardrail/u);
    assert.match(text, /Duel Signal Consensus Trigger/u);
    assert.match(text, /Duel Signal Consensus Protocol/u);
    assert.match(text, /Duel Signal Consensus Protocol Confidence/u);
    assert.match(text, /Duel Signal Protocol Trend/u);
    assert.match(text, /Duel Signal Protocol Risk/u);
    assert.match(text, /Duel Signal Protocol Regime/u);
    assert.match(text, /Duel Signal Protocol Cadence/u);
    assert.match(text, /Duel Signal Protocol Pressure/u);
    assert.match(text, /Duel Signal Protocol Command/u);
    assert.match(text, /Duel Signal Protocol Script/u);
    assert.match(text, /Protocol Confidence Points/u);
    assert.match(text, /Handoff Points/u);
    assert.match(text, /Consensus Points/u);
    assert.match(text, /Signal Points/u);
    assert.match(text, /Duel Snapshot/u);
    assert.match(text, /Duel Action Plan/u);
    assert.match(text, /Duel Gap Trend/u);
    assert.match(text, /Lead-Rival/u);
    assert.match(text, /Neck and neck/u);
    assert.match(text, /Lead is clear/u);
    assert.match(text, /Lead runaway/u);
    assert.match(text, /Coin flip/u);
    assert.match(text, /Lean lead/u);
    assert.match(text, /Strong lead/u);
    assert.match(text, /Execute Lead Now/u);
    assert.match(text, /Probe Rival First/u);
    assert.match(text, /Lead bias/u);
    assert.match(text, /Rival bias/u);
    assert.match(text, /Hold bias/u);
    assert.match(text, /Split signal/u);
    assert.match(text, /recent calls/u);
    assert.match(text, /Steady/u);
    assert.match(text, /Mixed/u);
    assert.match(text, /Volatile/u);
    assert.match(text, /Execute now/u);
    assert.match(text, /Ready with guardrails/u);
    assert.match(text, /Cautious go/u);
    assert.match(text, /Probe before commit/u);
    assert.match(text, /Delay execution/u);
    assert.match(text, /Split test ready/u);
    assert.match(text, /Hold confirmation/u);
    assert.match(text, /Immediate window/u);
    assert.match(text, /Staged window/u);
    assert.match(text, /Probe window/u);
    assert.match(text, /Hold window/u);
    assert.match(text, /Parallel window/u);
    assert.match(text, /Adaptive window/u);
    assert.match(text, /Pause guardrail/u);
    assert.match(text, /Dual-lane guardrail/u);
    assert.match(text, /Single-lane guardrail/u);
    assert.match(text, /Checkpoint guardrail/u);
    assert.match(text, /Probe guardrail/u);
    assert.match(text, /Adaptive guardrail/u);
    assert.match(text, /No trigger/u);
    assert.match(text, /Trigger split replay/u);
    assert.match(text, /Trigger immediate execute/u);
    assert.match(text, /Trigger staged execute/u);
    assert.match(text, /Trigger probe execute/u);
    assert.match(text, /Trigger watch execute/u);
    assert.match(text, /Standby protocol/u);
    assert.match(text, /Parallel protocol/u);
    assert.match(text, /Sprint protocol/u);
    assert.match(text, /Checkpoint protocol/u);
    assert.match(text, /Probe protocol/u);
    assert.match(text, /Adaptive protocol/u);
    assert.match(text, /Protocol Prime/u);
    assert.match(text, /Protocol Ready/u);
    assert.match(text, /Protocol Watch/u);
    assert.match(text, /Protocol Fragile/u);
    assert.match(text, /Low protocol risk/u);
    assert.match(text, /Medium protocol risk/u);
    assert.match(text, /High protocol risk/u);
    assert.match(text, /Breakout protocol lane/u);
    assert.match(text, /Stable protocol lane/u);
    assert.match(text, /Probe protocol lane/u);
    assert.match(text, /Whipsaw protocol lane/u);
    assert.match(text, /Cooling protocol lane/u);
    assert.match(text, /Fragile protocol lane/u);
    assert.match(text, /Burst cadence/u);
    assert.match(text, /Rhythm cadence/u);
    assert.match(text, /Probe cadence/u);
    assert.match(text, /Watch cadence/u);
    assert.match(text, /Hold cadence/u);
    assert.match(text, /Surge pressure/u);
    assert.match(text, /Stable pressure/u);
    assert.match(text, /Probe pressure/u);
    assert.match(text, /Caution pressure/u);
    assert.match(text, /Freeze pressure/u);
    assert.match(text, /Launch command/u);
    assert.match(text, /Stage command/u);
    assert.match(text, /Probe command/u);
    assert.match(text, /Watch command/u);
    assert.match(text, /Hold command/u);
    assert.match(text, /Split command/u);
    assert.match(text, /Execute lead now script/u);
    assert.match(text, /Stage checkpoint script/u);
    assert.match(text, /Probe compare script/u);
    assert.match(text, /Watch refresh script/u);
    assert.match(text, /Hold and wait script/u);
    assert.match(text, /Split replay script/u);
    assert.match(text, /avg swing/u);
    assert.match(text, /Rising \+/u);
    assert.match(text, /Falling -/u);
    assert.match(text, /Low shift risk/u);
    assert.match(text, /Medium shift risk/u);
    assert.match(text, /High shift risk/u);
    assert.match(text, /shifts/u);
    assert.match(text, /join\(" → "\)/u);
    assert.match(text, /confidence /u);
    assert.match(text, /stability /u);
    assert.match(text, /Calm /u);
    assert.match(text, /Active /u);
    assert.match(text, /Choppy /u);
    assert.match(text, /Charge/u);
    assert.match(text, /Advance/u);
    assert.match(text, /Recheck/u);
    assert.match(text, /Probe/u);
    assert.match(text, /Watch/u);
    assert.match(text, /Momentum breakout/u);
    assert.match(text, /Stable lane/u);
    assert.match(text, /Whipsaw risk/u);
    assert.match(text, /Transition zone/u);
    assert.match(text, /Rotation watch/u);
    assert.match(text, /Prime /u);
    assert.match(text, /Ready /u);
    assert.match(text, /Fragile /u);
    assert.match(text, /Lead sprint/u);
    assert.match(text, /Lead push/u);
    assert.match(text, /Rival probe/u);
    assert.match(text, /Hold & scan/u);
    assert.match(text, /Split test/u);
    assert.match(text, /Lead handoff/u);
    assert.match(text, /Rival handoff/u);
    assert.match(text, /Hold handoff/u);
    assert.match(text, /Split handoff/u);
    assert.match(text, /Mixed handoff/u);
    assert.match(text, /Escalating \+/u);
    assert.match(text, /Softening -/u);
    assert.match(text, /Aligned Lead/u);
    assert.match(text, /Aligned Rival/u);
    assert.match(text, /Hold consensus/u);
    assert.match(text, /Split consensus/u);
    assert.match(text, /Conflict/u);
    assert.match(text, /Lead consensus/u);
    assert.match(text, /Rival consensus/u);
    assert.match(text, /Mixed consensus/u);
    assert.match(text, /Low consensus risk/u);
    assert.match(text, /Medium consensus risk/u);
    assert.match(text, /High consensus risk/u);
    assert.match(text, /Strengthening \+/u);
    assert.match(text, /Drifting -/u);
    assert.match(text, /Open Rival/u);
    assert.match(text, /Copy Duel/u);
    assert.match(text, /Copy Duel Call \(Alt\+C\)/u);
    assert.match(text, /Copy Duel Snapshot \(Shift\+S\)/u);
    assert.match(text, /Copy Duel Signals \(Alt\+S\)/u);
    assert.match(text, /Copy Signal Handoff/u);
    assert.match(text, /Copy Signal Consensus/u);
    assert.match(text, /Copy Signal Command/u);
    assert.match(text, /Copy Signal Protocol/u);
    assert.match(text, /Download Signal Handoff/u);
    assert.match(text, /Download Signal Consensus/u);
    assert.match(text, /Download Signal Command/u);
    assert.match(text, /Download Signal Protocol/u);
    assert.match(text, /Copy Duel Plan \(Shift\+Q\)/u);
    assert.match(text, /Copy Decision Brief/u);
    assert.match(text, /Download Decision Brief \(Alt\+D\)/u);
    assert.match(text, /Toggle Duel Pair \(Alt\+Z\)/u);
    assert.match(text, /Run Duel Pair \(Alt\+Q\)/u);
    assert.match(text, /Run Duel Call \(Alt\+M\)/u);
    assert.match(text, /Run Signal Handoff/u);
    assert.match(text, /Run Signal Consensus/u);
    assert.match(text, /Run Signal Protocol/u);
    assert.match(text, /Run Signal Command \(Alt\+L\)/u);
    assert.match(text, /Run Signal Command/u);
    assert.match(text, /Run Rival Action/u);
    assert.match(text, /Two-step sprint ready/u);
    assert.match(text, /One side blocked/u);
    assert.match(text, /Both sides blocked/u);
    assert.match(text, /gap /u);
    assert.match(text, /lead→/u);
    assert.match(text, /rival→/u);
    assert.match(text, /Momentum/u);
    assert.match(text, /Heating \+/u);
    assert.match(text, /Cooling -/u);
    assert.match(text, /Rising \+/u);
    assert.match(text, /Falling -/u);
    assert.match(text, /Widening \+/u);
    assert.match(text, /Closing -/u);
    assert.match(text, /Flat/u);
    assert.match(text, /Steady/u);
    assert.match(text, /Baseline/u);
    assert.match(text, /heat-up/u);
    assert.match(text, /heat-down/u);
    assert.match(text, /heat-flat/u);
    assert.match(text, /tone-hot/u);
    assert.match(text, /tone-strong/u);
    assert.match(text, /tone-warm/u);
    assert.match(text, /tone-cool/u);
    assert.match(text, /Focus first /u);
    assert.match(text, /Aha candidate/u);
    assert.match(text, /Focus/u);
    assert.match(text, /Aha #/u);
    assert.match(text, /nudge-pool/u);
    assert.match(text, /Aha pool/u);
    assert.match(text, /Cycle with Shift\+N/u);
    assert.match(text, /nudge-actions/u);
    assert.match(text, /id="queueActionBanner"/u);
    assert.match(text, /id="recoveryRadar"/u);
    assert.match(text, /Recovery Radar/u);
    assert.match(text, /history-badge/u);
    assert.match(text, /0\/5/u);
    assert.match(text, /No recovery runs yet/u);
    assert.match(text, /Copy Recovery Summary/u);
    assert.match(text, /Download Summary/u);
    assert.match(text, /Previous Run/u);
    assert.match(text, /Next Run/u);
    assert.match(text, /Latest Run/u);
    assert.match(text, /Clear Radar/u);
    assert.match(text, /id="recoveryRadarTrend"/u);
    assert.match(text, /Trend vs previous/u);
    assert.match(text, /Trend Status/u);
    assert.match(text, /Step failed delta/u);
    assert.match(text, /trendStepDeltaExtractBtn/u);
    assert.match(text, /Click again to clear step filter/u);
    assert.match(text, /Click again to clear failed filter/u);
    assert.match(text, /Edit Context Filters/u);
    assert.match(text, /Focus Priority/u);
    assert.match(text, /trendFocusModeSmartBtn/u);
    assert.match(text, /trendFocusModeQueryFirstBtn/u);
    assert.match(text, /trendFocusModeStepFirstBtn/u);
    assert.match(text, /Query First/u);
    assert.match(text, /Step First/u);
    assert.match(text, /Step focus inactive/u);
    assert.match(text, /Choose a step delta to enable context jump/u);
    assert.match(text, /Auto-pick Search\/Retryable when active/u);
    assert.match(text, /filter-attention/u);
    assert.match(text, /Clear Step Focus/u);
    assert.match(text, /Clear Failed Filter/u);
    assert.match(text, /Filter Context/u);
    assert.match(text, /aria-pressed=/u);
    assert.match(text, /id="recoveryRadarTimeline"/u);
    assert.match(text, /History keeps last 5 recovery runs/u);
    assert.match(text, /Open Sample/u);
    assert.match(text, /Filter Step/u);
    assert.match(text, /recovery-step-grid/u);
    assert.match(text, /id="focusChips"/u);
    assert.match(text, /id="statusLegend"/u);
    assert.match(text, /id="recoveryFocusModeFilter"/u);
    assert.match(text, /Focus Priority: Smart/u);
    assert.match(text, /Focus Priority: Query First/u);
    assert.match(text, /Focus Priority: Step First/u);
    assert.match(text, /title="Focus Priority: Smart\. Auto-pick Search\/Retryable when active, otherwise jump by failed step\."/u);
    assert.match(text, /aria-label="Focus Priority: Smart\. Auto-pick Search\/Retryable when active, otherwise jump by failed step\."/u);
    assert.match(text, /id="detailModeChips"/u);
    assert.match(text, /id="detailSectionNav"/u);
    assert.match(text, /data-focus="ready"/u);
    assert.match(text, /Focus Mode \(F\)/u);
    assert.match(text, /Advanced Panels \(A\)/u);
    assert.match(text, /Aha Snapshot/u);
    assert.match(text, /Quick Actions/u);
    assert.match(text, /Recommended Action/u);
    assert.match(text, /Process & Regenerate/u);
    assert.match(text, /Ship & Export/u);
    assert.match(text, /Maintain Queue/u);
    assert.match(text, /Recovery Playbook/u);
    assert.match(text, /Recovery Priority:/u);
    assert.match(text, /Shipping Playbook/u);
    assert.match(text, /Next Recommended Move/u);
    assert.match(text, /Primary Next Step/u);
    assert.match(text, /id="detailActionBanner"/u);
    assert.match(text, /Queue Recommended/u);
    assert.match(text, /hero-recommendation/u);
    assert.match(text, /detail-hero/u);
    assert.match(text, /detailHeroStory/u);
    assert.match(text, /hero-story/u);
    assert.match(text, /hero-duel/u);
    assert.match(text, /duel-call-pill/u);
    assert.match(text, /duel-call-trend-inline/u);
    assert.match(text, /duel-call-confidence-inline/u);
    assert.match(text, /duel-call-stability-inline/u);
    assert.match(text, /duel-call-risk-inline/u);
    assert.match(text, /duel-call-sequence-inline/u);
    assert.match(text, /duel-signal-inline/u);
    assert.match(text, /duel-signal-pulse-inline/u);
    assert.match(text, /duel-signal-volatility-inline/u);
    assert.match(text, /duel-signal-outlook-inline/u);
    assert.match(text, /duel-signal-regime-inline/u);
    assert.match(text, /duel-signal-conviction-inline/u);
    assert.match(text, /duel-signal-handoff-inline/u);
    assert.match(text, /duel-signal-handoff-trend-inline/u);
    assert.match(text, /duel-signal-handoff-momentum-inline/u);
    assert.match(text, /duel-signal-consensus-inline/u);
    assert.match(text, /duel-signal-consensus-trend-inline/u);
    assert.match(text, /duel-signal-consensus-momentum-inline/u);
    assert.match(text, /duel-signal-consensus-risk-inline/u);
    assert.match(text, /duel-signal-consensus-stability-inline/u);
    assert.match(text, /duel-signal-consensus-readiness-inline/u);
    assert.match(text, /duel-signal-consensus-window-inline/u);
    assert.match(text, /duel-signal-consensus-guardrail-inline/u);
    assert.match(text, /duel-signal-consensus-trigger-inline/u);
    assert.match(text, /duel-signal-consensus-protocol-inline/u);
    assert.match(text, /duel-signal-consensus-protocol-confidence-inline/u);
    assert.match(text, /duel-signal-consensus-protocol-trend-inline/u);
    assert.match(text, /duel-signal-consensus-protocol-risk-inline/u);
    assert.match(text, /duel-signal-consensus-protocol-regime-inline/u);
    assert.match(text, /duel-signal-consensus-protocol-cadence-inline/u);
    assert.match(text, /duel-signal-consensus-protocol-pressure-inline/u);
    assert.match(text, /duel-signal-consensus-protocol-command-inline/u);
    assert.match(text, /duel-signal-consensus-protocol-script-inline/u);
    assert.match(text, /duel-signal-consensus-protocol-chart-inline/u);
    assert.match(text, /duel-signal-consensus-chart-inline/u);
    assert.match(text, /duel-signal-handoff-chart-inline/u);
    assert.match(text, /duel-signal-chart-inline/u);
    assert.match(text, /duel-snapshot-inline/u);
    assert.match(text, /duel-plan-inline/u);
    assert.match(text, /duel-gap-pill/u);
    assert.match(text, /duel-edge-pill/u);
    assert.match(text, /hero-brief/u);
    assert.match(text, /Brief Context/u);
    assert.match(text, /Queue Storyline/u);
    assert.match(text, /Copy Duel/u);
    assert.match(text, /Copy Duel Call \(Alt\+C\)/u);
    assert.match(text, /Copy Duel Snapshot \(Shift\+S\)/u);
    assert.match(text, /Copy Duel Signals \(Alt\+S\)/u);
    assert.match(text, /Copy Signal Handoff/u);
    assert.match(text, /Copy Signal Consensus/u);
    assert.match(text, /Copy Signal Command/u);
    assert.match(text, /Copy Signal Protocol/u);
    assert.match(text, /Download Signal Handoff/u);
    assert.match(text, /Download Signal Consensus/u);
    assert.match(text, /Download Signal Command/u);
    assert.match(text, /Download Signal Protocol/u);
    assert.match(text, /Copy Duel Plan \(Shift\+Q\)/u);
    assert.match(text, /Copy Decision Brief/u);
    assert.match(text, /Download Decision Brief \(Alt\+D\)/u);
    assert.match(text, /Toggle Duel Pair \(Alt\+Z\)/u);
    assert.match(text, /Run Duel Pair \(Alt\+Q\)/u);
    assert.match(text, /Run Duel Call \(Alt\+M\)/u);
    assert.match(text, /Run Signal Handoff/u);
    assert.match(text, /Run Signal Consensus/u);
    assert.match(text, /Run Signal Protocol/u);
    assert.match(text, /Run Signal Command \(Alt\+L\)/u);
    assert.match(text, /Run Signal Command/u);
    assert.match(text, /Open Lead/u);
    assert.match(text, /Open Rival/u);
    assert.match(text, /hero-kicker/u);
    assert.match(text, /Aha Momentum · Ready to ship now/u);
    assert.match(text, /Blocked Recovery/u);
    assert.match(text, /status-chip/u);
    assert.match(text, /status-rail-track/u);
    assert.match(text, /status-rail-caption/u);
    assert.match(text, /Flow stage:/u);
    assert.match(text, /insight-pills/u);
    assert.match(text, /insight-pill/u);
    assert.match(text, /aha-rank-chip/u);
    assert.match(text, /Aha Rank #/u);
    assert.match(text, /rank-top/u);
    assert.match(text, /duel-role-chip/u);
    assert.match(text, /role-lead/u);
    assert.match(text, /role-rival/u);
    assert.match(text, /role-observer/u);
    assert.match(text, /Duel Role/u);
    assert.match(text, /Lead/u);
    assert.match(text, /Rival/u);
    assert.match(text, /Observer/u);
    assert.match(text, /aha-gap-line/u);
    assert.match(text, /gap-lead/u);
    assert.match(text, /gap-chase/u);
    assert.match(text, /gap-trail/u);
    assert.match(text, /aha-lead/u);
    assert.match(text, /aha-chase/u);
    assert.match(text, /aha-trail/u);
    assert.match(text, /Lead Gap/u);
    assert.match(text, /Lead now/u);
    assert.match(text, /Keep shipping momentum/u);
    assert.match(text, /Close gap to lead/u);
    assert.match(text, /Trail lead/u);
    assert.match(text, /aha-rank-delta/u);
    assert.match(text, /delta-up/u);
    assert.match(text, /delta-down/u);
    assert.match(text, /→0/u);
    assert.match(text, /Impact: High/u);
    assert.match(text, /Urgency: Now/u);
    assert.match(text, /score-meter-track/u);
    assert.match(text, /score-meter-fill/u);
    assert.match(text, /Score: Unscored/u);
    assert.match(text, /High confidence/u);
    assert.match(text, /freshness-chip/u);
    assert.match(text, /Updated: unknown/u);
    assert.match(text, /Updated: just now/u);
    assert.match(text, /aha-index/u);
    assert.match(text, /aha-index-chip/u);
    assert.match(text, /Aha Index/u);
    assert.match(text, /Hot Now/u);
    assert.match(text, /next-move-line/u);
    assert.match(text, /next-move-chip/u);
    assert.match(text, /Next Move/u);
    assert.match(text, /press M/u);
    assert.match(text, /Mirrors global action status/u);
    assert.match(text, /Top actions are pinned in the header/u);
    assert.match(text, /Primary shipping action is already pinned in header/u);
    assert.match(text, /Export Snapshot/u);
    assert.match(text, /Copy Latest Paths/u);
    assert.match(text, /Artifacts JSON/u);
  });
});

test("exports route serves markdown file content", async () => {
  const repoRoot = resolve(fileURLToPath(new URL("../../../", import.meta.url)));
  const exportDir = mkdtempSync(join(repoRoot, "exports", "web-test-"));
  const filePath = join(exportDir, "card.md");
  writeFileSync(filePath, "# hello export\n", "utf-8");

  try {
    await withServer(async (baseUrl) => {
      const relative = filePath.replace(repoRoot + "/", "");
      const res = await fetch(baseUrl + "/" + relative);
      assert.equal(res.status, 200);
      assert.equal(res.headers.get("content-type"), "text/markdown; charset=utf-8");
      assert.equal(await res.text(), "# hello export\n");
    });
  } finally {
    rmSync(exportDir, { recursive: true, force: true });
  }
});

test("exports route blocks path traversal", async () => {
  await withServer(async (baseUrl) => {
    const target = new URL(baseUrl);
    const statusCode = await new Promise<number>((resolveStatus, rejectStatus) => {
      const req = httpRequest(
        {
          hostname: target.hostname,
          port: Number(target.port),
          path: "/exports/../package.json",
          method: "GET",
        },
        (res) => {
          resolveStatus(res.statusCode ?? 0);
        },
      );
      req.on("error", rejectStatus);
      req.end();
    });
    assert.equal(statusCode, 403);
  });
});

test("exports route returns 404 for missing file", async () => {
  await withServer(async (baseUrl) => {
    const res = await fetch(baseUrl + "/exports/not-found-file.md");
    assert.equal(res.status, 404);
  });
});
